[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "specsy-online"
version = "0.8.2"
readme = "README.md"
requires-python = ">=3.11,<3.15"
license = "GPL-3.0-or-later"
authors = [{name = "Vital Fernández", email = "vgf@stsci.edu"}]
description = "Streamlit wrapper for Specsy functions"
dependencies = ["aspect-stable>=0.7.dev3",
                "lime-stable[full]>=2.2.dev6",
                "innate-stable>=0.2.1",
                "specsy[tensors]>=0.9.dev5",
                "pyneb~=1.1.28",
                "tomlkit~=0.14.0",
                "bokeh==3.9.0",
                "streamlit==1.55.0",
                "streamlit_bokeh==3.9.0",
                "streamlit-authenticator==0.4.2",
                "st-gsheets-connection~=0.1",
                "google-api-python-client~=2.187.0"]

[tool.setuptools.packages.find]
where = ["."]
include = ["specsy_online*"]

[project.scripts]
specsy = "specsy_online.launcher:main"

[tool.setuptools.package-data]
specsy_online = ["resources/data/*",
                 "resources/images/*",
                 ".streamlit/config.toml"]